FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY src/ ./src/
# COPY packages/ ./packages/ # Don't copy "packages/" directory if you don't need it

RUN uv sync --extra np --no-dev

ENV PATH="/app/.venv/bin:$PATH"
